### ISSUE TITLE
Right overflow by n pixels

### ISSUE THREAD

**Issue by cerioalex** [iamedriancamacho/05BudgetApp#4]
'Right Overflowed By 15 Pixels' found if more than 2 categories exist.

**Comment by iamedriancamacho** [comment]
Can you provide us a screenshot and replicate the said issue? Thanks

**Comment by cerioalex** [comment]
<img width="360" alt="Screen Shot 2021-03-03 at 9 19 48 PM" src="https://user-images.githubusercontent.com/75462501/109812083-939d4c80-7c66-11eb-95ad-71fc5c9dee94.png">

<img width="368" alt="Screen Shot 2021-03-03 at 9 20 24 PM" src="https://user-images.githubusercontent.com/75462501/109812073-913af280-7c66-11eb-99e1-9d8ba79fb61e.png">

**Comment by iamedriancamacho** [comment]
Good day!

The team is currently solving this issue. 
Furthermore, I would advise you to commit to the same branch because the recent developing branch is still in progress. Thanks

**Comment by iamedriancamacho** [comment]
Hello. The team recently solved this error. Can you check it at your end? Leave a message if the issue persists.

**Comment by iamedriancamacho** [comment]
> 'Right Overflowed By 15 Pixels' found if more than 2 categories exist.

Hello. The team recently solved this error. Can you check it at your end? Leave a message if the issue persists.

**Comment by cerioalex** [comment]
I already tried the updated one, but it seems that there is still a single problem regarding 'RenderFlex overflowed by 21 pixels on the right'.

![Uploading Screen Shot 2021-03-14 at 12.39.02 AM.png…](
<img width="1440" alt="Screen Shot 2021-03-14 at 12 39 30 AM" src="https://user-images.githubusercontent.com/75462501/111037285-5f900b80-845e-11eb-87f5-9fad0d625d05.png">


<img width="1440" alt="Screen Shot 2021-03-14 at 12 38 36 AM" src="https://user-images.githubusercontent.com/75462501/111037271-59019400-845e-11eb-85f6-55fecaa8fdf9.png">

**Comment by cerioalex** [comment]
I already tried the updated one, but it seems that there is still a single problem regarding 'RenderFlex overflowed by 21 pixels on the right'.

<img width="323" alt="Screen Shot 2021-03-14 at 12 45 42 AM" src="https://user-images.githubusercontent.com/75462501/111037386-b269c300-845e-11eb-80a4-a7fd4cf119d9.png">
<img width="327" alt="Screen Shot 2021-03-14 at 12 45 54 AM" src="https://user-images.githubusercontent.com/75462501/111037389-b564b380-845e-11eb-8c2d-31b697f8caa7.png">
<img width="318" alt="Screen Shot 2021-03-14 at 12 46 02 AM" src="https://user-images.githubusercontent.com/75462501/111037391-b695e080-845e-11eb-9889-b70bd920b5f5.png">

**Comment by iamedriancamacho** [comment]
> I already tried the updated one, but it seems that there is still a single problem regarding 'RenderFlex overflowed by 21 pixels on the right'.
> 
> <img alt="Screen Shot 2021-03-14 at 12 45 42 AM" width="323" src="https://user-images.githubusercontent.com/75462501/111037386-b269c300-845e-11eb-80a4-a7fd4cf119d9.png">
> 
> <img alt="Screen Shot 2021-03-14 at 12 45 54 AM" width="327" src="https://user-images.githubusercontent.com/75462501/111037389-b564b380-845e-11eb-8c2d-31b697f8caa7.png">
> 
> <img alt="Screen Shot 2021-03-14 at 12 46 02 AM" width="318" src="https://user-images.githubusercontent.com/75462501/111037391-b695e080-845e-11eb-9889-b70bd920b5f5.png">

Good day, 
I believe that you haven't fetched the recent git. Please ensure first that the recent git has been picked. You should be seeing the main branch as our recent git. Thanks

**Comment by cerioalex** [comment]
Yes, I already did. I used the updated version but it seems like if the category name is lengthy, it will produce an exception of 'A Renderflex overflowed by 18 pixels on the right'. 
<img width="315" alt="Screen Shot 2021-03-16 at 1 16 12 PM" src="https://user-images.githubusercontent.com/75462501/111259441-d7765580-8659-11eb-9ecf-351167baa662.png">
<img width="318" alt="Screen Shot 2021-03-16 at 1 16 24 PM" src="https://user-images.githubusercontent.com/75462501/111259460-df35fa00-8659-11eb-8a7d-1d5bae69f818.png">

**Comment by iamedriancamacho** [comment]
> Yes, I already did. I used the updated version but it seems like if the category name is lengthy, it will produce an exception of 'A Renderflex overflowed by 18 pixels on the right'.
> <img alt="Screen Shot 2021-03-16 at 1 16 12 PM" width="315" src="https://user-images.githubusercontent.com/75462501/111259441-d7765580-8659-11eb-9ecf-351167baa662.png">
> <img alt="Screen Shot 2021-03-16 at 1 16 24 PM" width="318" src="https://user-images.githubusercontent.com/75462501/111259460-df35fa00-8659-11eb-8a7d-1d5bae69f818.png">

I am 100% sure that you are not on the recent git. By now, all processes (finished development process) are located on the main branch, which is our recent git, with a description ''Merge pull request #14 from iamedriancamacho/Finale'. 

There are two ways of identifying that you are on the current git.
1. The recent git, 'main' branch, that you should be seeing is located on the lower--left of your VS Code.
2. On our recent UI, The leading Widget does not exist anymore.
