### ISSUE TITLE
Cannot delete category

### ISSUE THREAD

**Issue by cerioalex** [iamedriancamacho/05BudgetApp#5]
It can delete/remove a category, but once I refresh the app, the deleted category will appear once again.

**Comment by iamedriancamacho** [comment]
As per the direction of the project description, Categories should not be deleted as to not produce any errors in the program. However, with regards to the sliding UX, there isn't any option to deactivate one side of the 'Slide-to-delete' Widget. 

We will further look at other options on the methods of deactivating the other side of the 'Slide-to delete' Widget. Thanks

**Comment by cerioalex** [comment]
<img width="360" alt="Screen Shot 2021-03-03 at 9 19 48 PM" src="https://user-images.githubusercontent.com/75462501/109811915-60f35400-7c66-11eb-86b2-beed3131be2f.png">


<img width="368" alt="Screen Shot 2021-03-03 at 9 20 24 PM" src="https://user-images.githubusercontent.com/75462501/109811975-710b3380-7c66-11eb-8c5e-ad08a6bd6d52.png">

**Comment by iamedriancamacho** [comment]
If you have further clarifications with regards to the said issue, feel free to write it here. If none, would you be fine with closing this issue? Thanks
